### ISSUE TITLE
Developer Payout

### ISSUE THREAD

**Issue by MatthewSH** [halfpetal/CapesAPI#24]
This is suggestion **is not currently planned**, but something we should consider. We also need to make sure people are aware that we **would not have to payout if we do not want to or can't afford to**.

Say a developer (or Marketplace seller) wants to make some money with some capes. The could upgrade their account and sell back their currency. 

Say we use coins as our currency, and we're using USD for our real currency. Here's an example payment...

1. User buys 100 coins for $100 (1 to 1).
2. Developer sells capes for 4 coins.
3. User buys cape, cape is activated on account, and coins are transferred to the seller.
4. Developer requests payout from seller account ( #16 ) for the amount of 4 coins.
5. Capes API pays the developer $0.25 to 1 coin. So the payout is $1.

**Comment by Hexeption** [comment]
👉

**Comment by Kizburb** [comment]
I think it's a good idea.
